name: uniqmaker
description: A new Flutter project.
publish_to: 'none' # This prevents publishing to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  signature: ^6.0.0
  pdf: ^3.10.0
  printing: ^5.10.1
  open_file: ^3.3.1
  path_provider: ^2.1.3
  animated_bottom_navigation_bar: ^1.0.1
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  url_launcher: ^6.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  collection: ^1.17.2
  flutter_svg: ^2.1.0
  flutter_colorpicker: ^1.0.3
  mailer: ^6.0.0
  shimmer: ^3.0.0
  confetti: ^0.8.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15




flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/mug.png
    - assets/sac.png
    - assets/textile_white.png
    - assets/textile_black.png
    - assets/tote.png
    - assets/carnet.png
    - assets/stylo.png
    - assets/paraplui.png
    - assets/profile.jpg